In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [5]:
df=pd.read_csv(r'C:\Users\USER\Documents\Numpy\Prices.csv')
df.head()

,unique_id,price_paid,deed_date,postcode,property_type,new_build,estate_type,saon,paon,street,locality,district,county,transaction_category
0,30271714-703B-4D25-9ACA-E949676BB7AF,54000,01/01/1995,B29 7NS,T,N,F,NaN,38,FIRST AVENUE,SELLY PARK,BIRMINGHAM,WEST MIDLANDS,A
1,A7A688D7-15EB-4C90-B2B6-8268A9E5CEEF,37000,01/01/1995,B31 5DF,S,N,F,NaN,83,JOSIAH ROAD,BIRMINGHAM,BIRMINGHAM,WEST MIDLANDS,A
2,EBBF45BD-BB6B-4944-8DE2-50FC8F8311F0,165500,01/01/1995,B45 8LY,D,N,F,NaN,"BITTELL COTTAGE, 76",BITTELL ROAD,BARNT GREEN,BROMSGROVE,WORCESTERSHIRE,A
3,B819DB02-6562-473B-AFA1-81B60787C2A7,24000,02/01/1995,B29 5TW,T,N,F,NaN,358,ALWOLD ROAD,BIRMINGHAM,BIRMINGHAM,WEST MIDLANDS,A
4,91A7BA4B-849C-4CAD-A112-C26597578CC0,33000,02/01/1995,B44 8SA,T,N,F,NaN,155,BIRDBROOK ROAD,BIRMINGHAM,BIRMINGHAM,WEST MIDLANDS,A

In [7]:
x =df.drop(['unique_id', 'deed_date','saon', 'paon', 'street', 'locality', 'district','postcode', 'county'], axis = 1, inplace=True)
x

In [9]:
#drop value in row
x = df[df['property_type']!="O"]
x

        price_paid property_type new_build estate_type transaction_category
0            54000             T         N           F                    A
1            37000             S         N           F                    A
2           165500             D         N           F                    A
3            24000             T         N           F                    A
4            33000             T         N           F                    A
...            ...           ...       ...         ...                  ...
370966      110000             T         N           F                    B
370968      140000             F         N           L                    B
370969      125000             F         N           L                    B
370971      158000             T         N           F                    A
370972       60000             F         N           L                    A

[366826 rows x 5 columns]

In [11]:
x['new_build'] = x['new_build'].map({'Y':1, 'N':0})
x['estate_type']=x['estate_type'].map({'F':1, 'L':0})
x['transaction_category'] =x['transaction_category'].map({'A':1, 'B':0})
x

C:\Users\USER\AppData\Local\Temp\ipykernel_10352\765823370.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['new_build'] = x['new_build'].map({'Y':1, 'N':0})
C:\Users\USER\AppData\Local\Temp\ipykernel_10352\765823370.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['estate_type']=x['estate_type'].map({'F':1, 'L':0})
C:\Users\USER\AppData\Local\Temp\ipykernel_10352\765823370.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['transaction_category'] =x['transaction_category'].map({'A':1, 'B':0})

        price_paid property_type  new_build  estate_type  transaction_category
0            54000             T          0          1.0                     1
1            37000             S          0          1.0                     1
2           165500             D          0          1.0                     1
3            24000             T          0          1.0                     1
4            33000             T          0          1.0                     1
...            ...           ...        ...          ...                   ...
370966      110000             T          0          1.0                     0
370968      140000             F          0          0.0                     0
370969      125000             F          0          0.0                     0
370971      158000             T          0          1.0                     1
370972       60000             F          0          0.0                     1

[366826 rows x 5 columns]

In [13]:
x.head()

   price_paid property_type  new_build  estate_type  transaction_category
0       54000             T          0          1.0                     1
1       37000             S          0          1.0                     1
2      165500             D          0          1.0                     1
3       24000             T          0          1.0                     1
4       33000             T          0          1.0                     1

In [15]:
x

        price_paid property_type  new_build  estate_type  transaction_category
0            54000             T          0          1.0                     1
1            37000             S          0          1.0                     1
2           165500             D          0          1.0                     1
3            24000             T          0          1.0                     1
4            33000             T          0          1.0                     1
...            ...           ...        ...          ...                   ...
370966      110000             T          0          1.0                     0
370968      140000             F          0          0.0                     0
370969      125000             F          0          0.0                     0
370971      158000             T          0          1.0                     1
370972       60000             F          0          0.0                     1

[366826 rows x 5 columns]

In [17]:
x['property_type']=x['property_type'].astype('category').cat.codes
x[['property_type']]

C:\Users\USER\AppData\Local\Temp\ipykernel_10352\4284424630.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['property_type']=x['property_type'].astype('category').cat.codes

        property_type
0                   3
1                   2
2                   0
3                   3
4                   3
...               ...
370966              3
370968              1
370969              1
370971              3
370972              1

[366826 rows x 1 columns]

In [19]:
x.describe()

,price_paid,property_type,new_build,estate_type,transaction_category
count,3.668260e+05,366826.000000,366826.000000,366801.000000,366826.000000
mean,1.264243e+05,2.065254,0.085771,0.737648,0.972895
std,9.516301e+04,0.952083,0.280026,0.439914,0.162391
min,1.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,6.600000e+04,1.000000,0.000000,0.000000,1.000000
50%,1.100000e+05,2.000000,0.000000,1.000000,1.000000
75%,1.565000e+05,3.000000,0.000000,1.000000,1.000000
max,4.725000e+06,3.000000,1.000000,1.000000,1.000000

In [21]:
x.isnull().sum()

price_paid               0
property_type            0
new_build                0
estate_type             25
transaction_category     0
dtype: int64

In [23]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 366826 entries, 0 to 370972
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   price_paid            366826 non-null  int64
 1   property_type         366826 non-null  int8
 2   new_build             366826 non-null  int64
 3   estate_type           366801 non-null  float64
 4   transaction_category  366826 non-null  int64
dtypes: float64(1), int64(3), int8(1)
memory usage: 14.3 MB

In [25]:
#To fill missing value
x['estate_type'] = x['estate_type'].fillna(x['estate_type'].mode().iloc[0])
x.head()

C:\Users\USER\AppData\Local\Temp\ipykernel_10352\3730407280.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['estate_type'] = x['estate_type'].fillna(x['estate_type'].mode().iloc[0])

   price_paid  property_type  new_build  estate_type  transaction_category
0       54000              3          0          1.0                     1
1       37000              2          0          1.0                     1
2      165500              0          0          1.0                     1
3       24000              3          0          1.0                     1
4       33000              3          0          1.0                     1

In [27]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 366826 entries, 0 to 370972
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   price_paid            366826 non-null  int64
 1   property_type         366826 non-null  int8
 2   new_build             366826 non-null  int64
 3   estate_type           366826 non-null  float64
 4   transaction_category  366826 non-null  int64
dtypes: float64(1), int64(3), int8(1)
memory usage: 14.3 MB

In [29]:
X=x.drop('price_paid', axis=1)
X

        property_type  new_build  estate_type  transaction_category
0                   3          0          1.0                     1
1                   2          0          1.0                     1
2                   0          0          1.0                     1
3                   3          0          1.0                     1
4                   3          0          1.0                     1
...               ...        ...          ...                   ...
370966              3          0          1.0                     0
370968              1          0          0.0                     0
370969              1          0          0.0                     0
370971              3          0          1.0                     1
370972              1          0          0.0                     1

[366826 rows x 4 columns]

In [31]:
y = x['price_paid']

In [34]:
#splitting to train and test(20%)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [36]:
from sklearn import svm
from sklearn.linear_model import LogisticRegression

In [38]:
lg=LogisticRegression()
price_comp=lg.fit(X_train,y_train)

MemoryError: Unable to allocate 21.9 GiB for an array with shape (293460, 10004) and data type float64

In [ ]:
print('predicted: ',price.predict:(X_test))
print("")
print('original: ': np.array(y_test))